#!/bin/bash
set -o errexit

USER=statsdaemon
USER_HOME=/tmp

if [ "$1" = configure ]; then
    adduser --system \
            --quiet \
            --home "$USER_HOME" \
            --no-create-home \
            --disabled-password \
            --group "$USER"
fi

service statsdaemon start || true
